/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 new.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/new.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, -0.015]} scale={[1, 1, 4.568]}>
        <mesh geometry={nodes.card_1.geometry} material={materials.refl} />
        <mesh geometry={nodes.card_2.geometry} material={materials.base} />
      </group>
      <mesh geometry={nodes.clip.geometry} material={materials.metal} />
      <mesh geometry={nodes.clamp.geometry} material={materials.metal} />
    </group>
  )
}

useGLTF.preload('/new.glb')
